/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import gestor.MensajeroGestor;
import gestor.SolicitanteGestor;
import javax.swing.JOptionPane;
import negocio.Mensajero;
import negocio.Solicitante;
import util.RHException;

/**
 *
 * @author amirz
 */
public class VistaInicioSesion extends javax.swing.JFrame {
    
     SolicitanteGestor sg;
     Solicitante solicitante;
     MensajeroGestor mg;
     Mensajero mensajero;
     
    /**
     * Creates new form VistaInicioSesion
     */
    public VistaInicioSesion() {
        initComponents();
        sg = new SolicitanteGestor();
        mg = new MensajeroGestor();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInicioSolicitante = new javax.swing.JButton();
        btnInicioMensajero = new javax.swing.JButton();
        btnRegistroSolicitante = new javax.swing.JButton();
        btnRegistroMensajero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInicioSolicitante.setText("Inicio como solicitante");
        btnInicioSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSolicitanteActionPerformed(evt);
            }
        });

        btnInicioMensajero.setText("Inicio como mensajero");
        btnInicioMensajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioMensajeroActionPerformed(evt);
            }
        });

        btnRegistroSolicitante.setText("Registro de solicitante");

        btnRegistroMensajero.setText("Registro de mensajero");

        jLabel1.setText("Mensajería urbana");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInicioSolicitante, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(btnInicioMensajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistroSolicitante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistroMensajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInicioSolicitante)
                .addGap(18, 18, 18)
                .addComponent(btnInicioMensajero)
                .addGap(18, 18, 18)
                .addComponent(btnRegistroSolicitante)
                .addGap(18, 18, 18)
                .addComponent(btnRegistroMensajero)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioMensajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioMensajeroActionPerformed
        // Muestra un cuadro de diálogo de entrada de texto
        String textoIngresado = JOptionPane.showInputDialog("Inserte su id:");
        
        mensajero = new Mensajero();
        
        try { 
              System.out.println("Prueba");
              mensajero=mg.buscarmensajero(Integer.parseInt(textoIngresado));
              
          } catch (RHException f) {
              JOptionPane.showMessageDialog(null, f, "Error", JOptionPane.ERROR_MESSAGE);
              
        }  

        
        // Verifica el id del usuario
        if (solicitante != null) {
            // Poner acá lo que pasa cuando el usuario existe
            JOptionPane.showMessageDialog(null, "Inicio de sesión exitoso " + textoIngresado);
        } else {
            // Lo que pasa cuando el usuario no existe
            JOptionPane.showMessageDialog(null, "ERROR: Usuario no existe");
        }
    }//GEN-LAST:event_btnInicioMensajeroActionPerformed

    private void btnInicioSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSolicitanteActionPerformed
        // Muestra un cuadro de diálogo de entrada de texto
        String textoIngresado = JOptionPane.showInputDialog("Inserte su id:");
        
        solicitante = new Solicitante();
        
        try { 
              System.out.println("Prueba");
              solicitante=sg.buscarSolicitante(Integer.parseInt(textoIngresado));
              
          } catch (RHException f) {
              JOptionPane.showMessageDialog(null, f, "Error", JOptionPane.ERROR_MESSAGE);
              
        }  

        
        // Verifica el id del usuario
        if (solicitante != null) {
            // Poner acá lo que pasa cuando el usuario existe
            JOptionPane.showMessageDialog(null, "Inicio de sesión exitoso " + textoIngresado);
        } else {
            // Lo que pasa cuando el usuario no existe
            JOptionPane.showMessageDialog(null, "ERROR: Usuario no existe");
        }
    }//GEN-LAST:event_btnInicioSolicitanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnInicioMensajero;
    public javax.swing.JButton btnInicioSolicitante;
    public javax.swing.JButton btnRegistroMensajero;
    public javax.swing.JButton btnRegistroSolicitante;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables


}  
